services:
  - type: web
    name: cs492-bookstore-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore_db
          property: connectionString
    autoDeploy: true
